# Generated by Django 5.0.2 on 2024-02-29 03:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('INTERMEDIATE', 'Intermediate'), ('DIFFICULT', 'Difficult'), ('NONE', 'None')], default='NONE', max_length=20)),
            ],
            options={
                'db_table': 'assignment_difficulty',
            },
        ),
        migrations.CreateModel(
            name='AssignmentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'assignment_topic',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('university', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('open_to_research', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='INACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'user_status',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('estimated_duration', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('is_required', models.BooleanField(null=True)),
                ('assignment_difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assignmentdifficulty')),
                ('assignment_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assignmenttopic')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=100)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_num', models.IntegerField(null=True)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignment')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_student_was_added', models.DateTimeField(default=datetime.datetime.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'course_student',
            },
        ),
        migrations.CreateModel(
            name='StudentCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignment_was_assigned', models.DateTimeField(default=datetime.datetime.now)),
                ('date_completed', models.DateTimeField(null=True)),
                ('date_due', models.DateTimeField(null=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('is_for_grade', models.BooleanField(null=True)),
                ('grade', models.FloatField(null=True)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.assignment')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'student_course_assignment',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='user_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userstatus'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userstatus'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('user_status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userstatus')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
